version: '3.8'

services:
  api-app:
    image: rosecompany/api-app:staging
    restart: always
    environment:
      - API_INFO__VERSION=staging
    ports:
      - '8080:8080'
    networks:
      - rosecompany_network
networks:
  rosecompany_network:
    driver: bridge