version: '3.8'

services:
  api-app:
    image: mikenam/smart-restaurant-api:staging
    restart: always
    env_file:
      - .env
    environment:
      - API_INFO__VERSION=staging
    ports:
      - '8080:8080'
    networks:
      - rosecompany_network
networks:
  rosecompany_network:
    driver: bridge