postgres:
  host:
  user:
  pass:
  db:
  params: application_name=app-api
  gorm_debug: debug

redis:
  host:
  internal_port:
  db_idx: 0
  pass:


digital_ocean:
  storage_access_key:
  storage_secret_key:
  storage_region:
  storage_bucket:
  storage_endpoint:
  imgkit_output_endpoint:
  storage_acl:

http:
  max_idle_connection: 10
  idle_connection_timeout: 30

jwt_secret:
token_expired_time: 604800000

